site_name: UNISOC IoT Documents
site_url: https://unisoc.github.io
site_author: Dong.Xiang
site_description: UNISOC Documents
copyright: Â© Copyright 2018-2021 UNISOC members and individual contributors Last updated on Nov 20, 2018.

repo_url: https://github.com/unisoc/documentation
repo_name: Github
strict: true

theme:
  name: 'material'
  logo: 'extras/images/UNISOC_LOGO.jpg'
  palette:
    primary: 'Purple'
    accent: 'Green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true

markdown_extensions:
    - toc:
        permalink: True
    - sane_lists

nav:
- Home: 'index.md'
- Chips:
    - 'Overview': 'chip/index.md'
    - 'UWP5661': 'chip/UWP5661.md'
- Boards:
    - 'Overview': 'board/index.md'
    - '96Boards IVY5661': 'board/96b_ivy5661.md'
- SDK:
    - 'Overview': 'sdk/index.md'
    - 'Build UNISOC SDK': 'sdk/build.md'
    - 'Updating firmware': 'sdk/update_firmware.md'
    - 'Debugging': 'sdk/debug.md'
- Applications:
    - 'Overview': 'apps/index.md'
    - 'Wi-Fi Repeater': 'apps/wifi_repeater.md'
- Tools:
    - 'Overview': 'tools/index.md'
    - 'DLoader': 'tools/dloader.md'
- About: 'about.md'
